import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from "../components/Navbar";
import Image from "next/dist/client/legacy/image";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <div className={'w-full fixed h-16 z-50'}>
              <Navbar></Navbar>
          </div>
          <div className={'block h-[100vh] pt-16 relative border-2 border-black bg-[url("../public/images/main_background.png")] bg-cover'}>
              <div className={'absolute w-full bottom-0 h-[22vw]'}>
                  <Image src={'/images/main_bg.png'} layout={'fill'}></Image>
              </div>
              <div className={'w-full p-4 flex justify-between items-center'}>
                  <div className={'w-72 h-72 flex justify-center items-center relative'}>
                      <div className={'absolute z-0 top-0 left-0 w-full h-full'}>
                          <Image src={'/images/main_round.png'} layout={'fill'}></Image>
                      </div>
                      <p className={'z-[5] text-white font-player text-xl text-center'}>Total supply<br/><span className={'text-5xl'}>0/3000</span></p>
                  </div>
                  <div className={'w-3/5 mx-5 h-32 relative'}>
                      <Image src={'/images/logo.svg'} layout={'fill'}></Image>
                  </div>
                  <div className={'w-72 h-72 flex justify-center items-center relative'}>
                      <div className={'absolute z-0 top-0 left-0 w-full h-full'}>
                          <Image src={'/images/main_round.png'} layout={'fill'}></Image>
                      </div>
                      <p className={'z-[5] text-white font-player text-5xl text-center'}>WL<br/><span className={'text-5xl'}>0/500</span></p>
                  </div>
              </div>

          </div>
      </main>

    </div>
  )
}
